// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjfuwwlmibknhfylfyin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZnV3d2xtaWJrbmhmeWxmeWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjI2NzMsImV4cCI6MjA4ODUzODY3M30.rJgT9T6AzNkUcyNYMQ7LPpo4zXdxffclogDCAcvlUFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});